apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: default
spec:
  secretName: nginx-ingress-tls  # Secret name to store the certificate
  issuerRef:
    name: letsencrypt-prod  # ClusterIssuer reference
    kind: ClusterIssuer
  dnsNames:
    - kubeapp.smartnoticeboard.io  # Replace with your domain
